name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-3.29.0
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Install Flutter SDK
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.flutter
          curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.0-stable.tar.xz | tar -xJ -C ~/.flutter --strip-components=1

      - name: Add Flutter to PATH
        run: echo "${HOME}/.flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: .

      - name: Unzip production artifacts
        run: |
          unzip web-build.zip

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          pwd
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t thejohnmarkcustodio/informative-website:latest -f Dockerfile .
          docker push thejohnmarkcustodio/informative-website:latest

      - name: Update Helm Chart Repository
        run: |
          git clone https://github.com/thejohnmarkcustodio/informative-website-helm.git
          cd informative-website-helm
          sed -i 's|repository:.*|repository: thejohnmarkcustodio/informative-website|' informative-website/values.yaml
          sed -i 's|tag:.*|tag: latest|' informative-website/values.yaml
          git config --global user.email "thejohnmarkcustodio@gmail.com"
          git config --global user.name "thejohnmarkcustodio"
          git add informative-website/values.yaml
          git commit -m "Update image repository and tag"
          git push