# filepath: .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t thejohnmarkcustodio/informative-website:latest build/web
          docker push thejohnmarkcustodio/informative-website:latest

      - name: Update Helm Chart Repository
        run: |
          git clone https://github.com/thejohnmarkcustodio/informative-website-helm.git
          cd informative-website-helm
          sed -i 's|repository:.*|repository: thejohnmarkcustodio/informative-website|' informative-website/values.yaml
          sed -i 's|tag:.*|tag: latest|' informative-website/values.yaml
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add informative-website/values.yaml
          git commit -m "Update image repository and tag"
          git push