# filepath: .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: web-build
          path: build/web

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t your-docker-repo/informative_website:latest build/web
          docker push your-docker-repo/informative_website:latest
